"""
knowledge/build_index.py
------------------------
Build the knowledge index from the DOCUMENTS list.

Backend selection:
  DATABASE_URL set  → embed with OpenAI and INSERT into knowledge_documents (pgvector)
  DATABASE_URL unset → build FAISS index locally (original behaviour)

Run after any change to DOCUMENTS:
  python knowledge/build_index.py
"""

from __future__ import annotations

import os

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings

load_dotenv()

# ---------------------------------------------------------------------------
# Knowledge base
# ---------------------------------------------------------------------------

DOCUMENTS = [
    # ── Business model ────────────────────────────────────────────────────
    Document(
        page_content=(
            "The business model represents a retail pricing scenario. "
            "The company sells a product at a given unit price "
            "and invests in marketing to stimulate demand. "
            "Revenue is generated by selling units at the set price. "
            "Profit is the difference between revenue and total variable costs."
        ),
        metadata={"category": "business_model"},
    ),
    Document(
        page_content=(
            "The two decision variables in this model are price and marketing spend. "
            "Price is the unit sale price of the product, ranging from 10 to 50 EUR. "
            "Marketing spend is the monthly investment in marketing campaigns, "
            "ranging from 1,000 to 50,000 EUR. "
            "Both variables directly influence customer demand."
        ),
        metadata={"category": "business_model"},
    ),
    Document(
        page_content=(
            "The business constraint is that price must always exceed "
            "unit variable cost "
            "to ensure each unit sold generates a positive margin. "
            "Selling below cost leads to losses regardless of volume. "
            "The unit variable cost in this model is 10 EUR per unit."
        ),
        metadata={"category": "business_model"},
    ),
    # ── Causal model ──────────────────────────────────────────────────────
    Document(
        page_content=(
            "Demand depends on both price and marketing spend. "
            "Higher prices reduce demand due to price elasticity "
            "(negative effect). "
            "Higher marketing spend increases demand by attracting "
            "more customers (positive effect). "
            "The relationship is estimated by a machine learning "
            "model trained on historical sales data."
        ),
        metadata={"category": "causal_model"},
    ),
    Document(
        page_content=(
            "Revenue equals price multiplied by demand. "
            "As price increases, revenue is affected by two opposing forces: "
            "higher unit revenue per sale, but lower demand volume. "
            "The optimal price balances these two effects to maximise total revenue."
        ),
        metadata={"category": "causal_model"},
    ),
    Document(
        page_content=(
            "Cost equals demand multiplied by the unit variable cost. "
            "As demand increases, total costs increase proportionally. "
            "Fixed costs are not modelled in this version of the system. "
            "Only variable costs (cost per unit produced and sold) are considered."
        ),
        metadata={"category": "causal_model"},
    ),
    Document(
        page_content=(
            "Profit equals revenue minus total cost. "
            "Profit = (price × demand) − (unit_cost × demand) "
            "= demand × (price − unit_cost). "
            "Therefore, profit is determined by both the margin per unit "
            "(price − unit_cost) and the volume of units sold (demand). "
            "Maximising profit requires balancing both."
        ),
        metadata={"category": "causal_model"},
    ),
    # ── ML model ──────────────────────────────────────────────────────────
    Document(
        page_content=(
            "The demand prediction model is a Random Forest regressor "
            "trained on historical sales data containing price, "
            "marketing spend, and observed demand. "
            "Random Forests handle non-linear relationships and interactions "
            "between variables. "
            "The model captures the combined effect of price and marketing on demand."
        ),
        metadata={"category": "ml_model"},
    ),
    Document(
        page_content=(
            "The demand model is a machine learning estimator, "
            "not a deterministic formula. "
            "This means demand predictions carry uncertainty: "
            "the model generalises from "
            "training data and may not perfectly predict every scenario. "
            "Monte Carlo simulation is used to quantify and propagate this uncertainty."
        ),
        metadata={"category": "ml_model"},
    ),
    # ── Simulation ────────────────────────────────────────────────────────
    Document(
        page_content=(
            "Monte Carlo simulation runs the system model hundreds of times "
            "with random perturbations on the demand estimate "
            "to simulate real-world uncertainty. "
            "Each run samples a slightly different demand value, "
            "producing a distribution "
            "of possible profit outcomes rather than a single deterministic answer."
        ),
        metadata={"category": "simulation"},
    ),
    Document(
        page_content=(
            "The simulation output includes: expected profit (mean), "
            "profit standard deviation, 10th percentile profit "
            "(pessimistic scenario), 90th percentile profit "
            "(optimistic scenario), and downside risk percentage "
            "(fraction of runs where profit is negative). "
            "These statistics describe both the upside potential "
            "and downside risk of a decision."
        ),
        metadata={"category": "simulation"},
    ),
    Document(
        page_content=(
            "A high profit standard deviation indicates high uncertainty: "
            "the actual outcome "
            "could differ significantly from the expected value. "
            "A high downside risk percentage means the decision has "
            "a meaningful probability "
            "of resulting in a loss, even if the expected profit is positive."
        ),
        metadata={"category": "simulation"},
    ),
    Document(
        page_content=(
            "Simulation is used to answer 'what if' questions: "
            "what happens to profit "
            "if price is set to X and marketing to Y? "
            "It evaluates a specific scenario under uncertainty. "
            "Optimisation, by contrast, searches across many scenarios "
            "to find the best decision."
        ),
        metadata={"category": "simulation"},
    ),
    # ── Optimization ──────────────────────────────────────────────────────
    Document(
        page_content=(
            "The optimisation tool performs a grid search over the price range "
            "to find the price that maximises expected profit "
            "under Monte Carlo uncertainty. "
            "Marketing spend is held fixed at the default value "
            "during price optimisation. "
            "The result is the price and its associated expected profit distribution."
        ),
        metadata={"category": "optimization"},
    ),
    Document(
        page_content=(
            "Price optimisation answers questions like: "
            "'What price should I set to maximise profit?' "
            "The system evaluates the full price range, simulates each candidate price "
            "under uncertainty, "
            "and selects the price with the highest expected profit. "
            "The result includes not just the optimal price but also "
            "the expected risk at that price."
        ),
        metadata={"category": "optimization"},
    ),
    Document(
        page_content=(
            "The optimal price is not always the highest possible price. "
            "Setting price too high reduces demand significantly, "
            "which can reduce total profit "
            "even though the margin per unit is higher. "
            "The optimiser finds the price that best balances margin and volume."
        ),
        metadata={"category": "optimization"},
    ),
    # ── Interpretation ────────────────────────────────────────────────────
    Document(
        page_content=(
            "Price elasticity of demand measures how sensitive demand "
            "is to price changes. "
            "In this model, a 1 EUR increase in price reduces demand "
            "by approximately 1.6 units on average. "
            "This negative relationship is captured by the ML demand model. "
            "Understanding elasticity helps set prices that balance margin and volume."
        ),
        metadata={"category": "interpretation"},
    ),
    Document(
        page_content=(
            "Marketing ROI (return on investment) measures how much additional demand "
            "is generated per unit of marketing spend. "
            "In this model, each additional unit of marketing investment "
            "increases demand by approximately 0.9 units. "
            "Higher marketing ROI means marketing spend translates more efficiently "
            "into additional sales."
        ),
        metadata={"category": "interpretation"},
    ),
    # ── Architecture ──────────────────────────────────────────────────────
    Document(
        page_content=(
            "The system architecture follows a layered design: "
            "Data layer (historical sales) → ML model (demand estimator) → "
            "System model (causal DAG) → Simulation engine (Monte Carlo) → "
            "Optimisation layer (grid search) → Agent layer (LLM orchestration). "
            "The LLM does not compute decisions: it orchestrates deterministic "
            "analytical tools."
        ),
        metadata={"category": "architecture"},
    ),
    Document(
        page_content=(
            "The causal graph (DAG) represents the structural relationships "
            "between business variables: "
            "price → demand, marketing → demand, demand → revenue, demand → cost, "
            "revenue → profit, cost → profit. "
            "The graph is used to propagate decision values through the model "
            "in topological order. "
            "Adding new causal relationships requires only editing "
            "the graph definition."
        ),
        metadata={"category": "architecture"},
    ),
]


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def build_knowledge_index(index_path: str = "knowledge_index") -> None:
    """
    Build the knowledge index.

    Uses pgvector when DATABASE_URL is set, FAISS otherwise.
    """
    database_url = os.getenv("DATABASE_URL", "")
    if database_url:
        _build_pgvector(index_path)
    else:
        _build_faiss(index_path)


# ---------------------------------------------------------------------------
# pgvector backend
# ---------------------------------------------------------------------------


def _build_pgvector(index_path: str) -> None:
    print(f"Building pgvector index from {len(DOCUMENTS)} documents...")
    embeddings_model = OpenAIEmbeddings()

    from db.engine import get_session
    from db.models import KnowledgeDocument

    texts = [doc.page_content for doc in DOCUMENTS]
    vectors = embeddings_model.embed_documents(texts)

    with get_session() as session:
        # Clear existing documents before re-indexing
        session.query(KnowledgeDocument).delete()
        for doc, embedding in zip(DOCUMENTS, vectors):
            session.add(
                KnowledgeDocument(
                    content=doc.page_content,
                    category=doc.metadata.get("category"),
                    embedding=embedding,
                )
            )
    print(f"pgvector: inserted {len(DOCUMENTS)} documents into knowledge_documents.")


# ---------------------------------------------------------------------------
# FAISS backend (original behaviour)
# ---------------------------------------------------------------------------


def _build_faiss(index_path: str) -> None:
    from langchain_community.vectorstores import FAISS

    print(f"Building FAISS index from {len(DOCUMENTS)} documents...")
    embeddings = OpenAIEmbeddings()
    vectorstore = FAISS.from_documents(DOCUMENTS, embeddings)
    vectorstore.save_local(index_path)
    print(f"FAISS index saved to '{index_path}' ({len(DOCUMENTS)} docs indexed).")


if __name__ == "__main__":
    build_knowledge_index()
